services:
  - name: url-shortener
    type: web
    plan: free
    buildCommand: go build -o main .
    startCommand: ./main
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: url-shortener
          property: connectionString
      - key: PORT
        value: 10000 # Ensure your Go app listens on this port
    runtime: go

databases:
  - name: url-shortener
    plan: free
    postgresMajorVersion: "16"
